[{"img":"https://1.bp.blogspot.com/-QiVskp9ooP0/XS0sWFJyiZI/AAAAAAAANGs/2jZAyJEgGqsvGrVJSiWArb9Z0y1gg6pMwCLcBGAs/s400/Lionel%2BMessi.png","name":"Lionel Messi"},
{"img":"https://1.bp.blogspot.com/-rF69u0hLBfw/XS0sfMOQvwI/AAAAAAAANGw/sF549ABwXZcD8x8uqihAbSu74ZXKwZ8qwCLcBGAs/s400/Critiano%2BRonaldo.png","name":"Cristiano Ronaldo"},
{"img":"https://1.bp.blogspot.com/-CyCsCNlgqv0/XS0sjwmkoWI/AAAAAAAANG0/bGpO0p96Z-0zJL1i1qRgdYu4wqT7exqVwCLcBGAs/s400/Zinedine%2BZidane.png","name":"Zidane"},
{"img":"https://1.bp.blogspot.com/-FjJHnyNgSyA/XS0snsEBEGI/AAAAAAAANG4/J-GcEeGqrNgRTiuBudiVYQgEcKctItJ8gCLcBGAs/s400/Pele.png","name":"Pele"},
{"img":"https://1.bp.blogspot.com/-GCtpdWqQ9G4/XS0sr_URAuI/AAAAAAAANG8/Y70_gHloRMk9q2WvoXzvDeAANQ2QitK8QCLcBGAs/s400/Maradona.png","name":"Maradona"},
{"img":"https://1.bp.blogspot.com/-4Efp0TG63EA/XS0s-luDU6I/AAAAAAAANHU/55UeTUkLbagS7ESwwLm9nphzvmYl7vYbQCLcBGAs/s400/Manuel%2BNeuer.png","name":"Manuel Neuer"},
{"img":"https://th.bing.com/th/id/OIP.sDLaRaxeSPJHtP8gdTCmkgHaE8?pid=ImgDet&dpr=1.9","name":"Kylian Mbappe"},
{"img":"https://tse1.mm.bing.net/th?id=OIP.Jf9EH9aBLpEf8ZNzu1s-sQHaFP&pid=Api&P=0&w=565&h=400","name":"Neymar"},
{"img":"https://tse2.mm.bing.net/th?id=OIP.H603l7PRlTENbqhCKq5xswHaE7&pid=Api&P=0&w=601&h=400","name":"Casemiro"},
{"img":"https://tse2.mm.bing.net/th?id=OIF.P82aPvprRLj6QdANwP3SBA&pid=Api&P=0&w=474&h=315","name":"Erling Haaland"},
{"img":"https://tse1.mm.bing.net/th?id=OIP.txPHKNxDsd3SIrtUI0hCBwHaEK&pid=Api&P=0&w=711&h=400","name":"Mohamed Salah"},
{"img":"https://tse2.mm.bing.net/th?id=OIP.C1Uk0Tb8gFSIMNTC3lzczwHaEK&pid=Api&P=0&w=711&h=400","name":"Luka Modric"},
{"img":"https://tse1.mm.bing.net/th?id=OIP.vgOzCbR7B2AKsFxclhCMXgHaEK&pid=Api&P=0&w=711&h=400","name":"Phil Foden"},
{"img":"https://tse2.mm.bing.net/th?id=OIP.TI3D21Ld5B1PSbFuDGazhgHaEK&pid=Api&P=0&w=711&h=400","name":"Kun Aguero"},
{"img":"https://tse2.mm.bing.net/th?id=OIP.q1esGjPf9f8aZ2WnPy7kowHaE8&pid=Api&P=0&w=599&h=400","name":"Rodri"},
{"img":"https://tse1.mm.bing.net/th?id=OIP.BRZlAg41AM-gQFBGuJ7krwHaE7&pid=Api&P=0&w=600&h=400","name":"Karim Benzema"},
{"img":"https://tse2.mm.bing.net/th?id=OIF.Myks5W0n2XxdWo%2fF%2fBbbxg&pid=Api&P=0&w=474&h=266","name":"Robert Lewandowski"},
{"img":"https://tse1.mm.bing.net/th?id=OIP.JuObN8wkYygJQSVW9X2SBQHaE7&pid=Api&P=0&w=600&h=400","name":"Paulo Dybala"},
{"img":"https://tse2.mm.bing.net/th?id=OIP.8R_NEn9mqNOA4XsT1A-bDwHaE-&pid=Api&P=0&w=595&h=400","name":"Antony"},
{"img":"https://tse2.mm.bing.net/th?id=OIP.YKH-dilGtJ5OewCfSc-M_gHaE7&pid=Api&P=0&w=600&h=400","name":"Pedri"},
{"img":"https://tse1.mm.bing.net/th?id=OIP.ndcgIOvtHpzF-2BKhfwhmgHaEK&pid=Api&H=89&W=160","name":"Kevin De Bruyne"},
{"img":"https://tse1.mm.bing.net/th?id=OIP.Osk16tVrLU-iuHOWcy4gBwHaE8&pid=Api&P=0&w=600&h=400","name":"Sadio Mane"},
{"img":"https://tse2.mm.bing.net/th?id=OIP.nLYpI5IK1tljo0HVTbYK_QHaE8&pid=Api&P=0&w=600&h=400","name":"Virgil van Dijk"},
{"img":"https://tse1.mm.bing.net/th?id=OIP.qWHeVX2OxbsdlWLu9KxobAHaFb&pid=Api&P=0&w=546&h=400","name":"Vinicius Junior"},
{"img":"https://ovicsoft.com/wp-content/uploads/2022/06/Pratama-Arhan.jpeg","name":"Pratama Arhan"},
{"img":"https://ovicsoft.com/wp-content/uploads/2022/06/Witan-Sulaeman.jpeg","name":"Witan Sulaeman"},
{"img":"https://ovicsoft.com/wp-content/uploads/2022/06/Rizky-Ridho.jpeg","name":"Rizky Ridho"},
{"img":"https://ovicsoft.com/wp-content/uploads/2022/06/Saddam-Gaffar-.jpeg","name":"Saddam Gaffar"},
{"img":"https://ovicsoft.com/wp-content/uploads/2022/06/Braif-Fatari.jpeg","name":"Braif Fatari"},
{"img":"https://img.sportstars.id//2021/05/ve74i3/master_1Xb07mt06T_935.jpg","name":"Bambang Pamungkas"},
{"img":"https://img.sportstars.id//2021/07/p04ka6/master_1q46E47rgD_1934.jpg","name":"Boaz Solossa"},
{"img":"https://cdn1-production-images-kly.akamaized.net/PiLp_lKJ7t-ac74yi4_6HwWrQwM=/375x208/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/1258584/original/053765200_1465416577-Adityo_Darmadi.jpg","name":"Robby Darwis"},
{"img":"https://tse1.mm.bing.net/th?id=OIP.V_ETrrFPK2Oupd605aOw1QHaD6&pid=Api&P=0&w=757&h=400","name":"Hariono"},
{"img":"https://tse1.mm.bing.net/th?id=OIP.C2eWd-boAi5zAcPp24NPpwHaE9&pid=Api&P=0&w=597&h=400","name":"Ferdinand Sinaga"},
{"img":"https://tse2.mm.bing.net/th?id=OIP.kV6s-XAbrRPh6pZAzTqj4QHaD-&pid=Api&P=0&w=746&h=400","name":"Supardi"},
{"img":"https://tse1.mm.bing.net/th?id=OIP.O_AYBmoqDMRWeMNieBzR4wHaEp&pid=Api&P=0&w=637&h=400","name":"Choirul Huda"}]

